### ISSUE TITLE
Uploading image causes multipart EOF

### ISSUE THREAD

**Issue by gocs** [gocs/seaweedfs-test#1]
https://github.com/gocs/seaweedfs-test/blob/d60610dd7bf76739e8a54880c051ae98cee81ded/main.go#L42

**Comment by chrislusf** [comment]
https://github.com/gocs/seaweedfs-test/blob/master/pkg/store/store.go#L47

This is a reader to a FormFile. Need a reader to file content.

**Comment by gocs** [comment]
I'm not sure what you mean, but after searching simpler solution. I guess I just have to copy the file to a buffer.

**Comment by gocs** [comment]
> https://github.com/gocs/seaweedfs-test/blob/master/pkg/store/store.go#L47
> 
> This is a reader to a FormFile. Need a reader to file content.

I doubt why I need a reader when multipart.File is also a valid reader.
